name: Bug 反馈
description: 报告你遇到的 Bug
title: "[Bug] "
labels: ["bug"]
assignees: ["W1ndys"]
body:
  - type: input
    id: module_name
    attributes:
      label: 模块名称
      description: 请填写涉及的模块名称
      placeholder: 例如：用户管理模块
    validations:
      required: true
  - type: textarea
    id: problem_description
    attributes:
      label: 问题描述
      description: 请详细描述遇到的Bug，包括复现步骤、预期结果和实际结果
      placeholder: |
        **复现步骤：**
        1. 登录系统
        2. 点击"编辑个人资料"
        3. 修改用户名，然后点击保存
        
        **预期结果：** 用户名成功更新并显示"保存成功"提示
        
        **实际结果：** 页面卡住，控制台显示错误
        
        **错误信息：** (请粘贴错误日志或截图)
        
        **操作系统：** Windows 10 / macOS / Linux
      render: markdown
    validations:
      required: true
