name: 新功能需求
description: 提出一个新的功能或优化建议
title: "[功能] "
labels: ["enhancement", "feature"]
assignees: ["W1ndys"]
body:
  - type: input
    id: module_name
    attributes:
      label: 模块名称
      description: 请填写涉及的模块名称
      placeholder: 例如：报表生成模块
    validations:
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: 功能需求描述
      description: 请详细描述功能需求和期望解决的问题
      placeholder: |
        **需求描述：** 希望能够根据日期范围导出Excel格式的销售数据报表
        
        **现有问题：** 目前只能查看当天数据，无法进行历史数据分析
        
        **期望价值：** 解决历史数据分析难题，提高决策效率
        
        **建议方案：** 在报表页面增加日期选择器和导出按钮
        
        **优先级：** 高/中/低
      render: markdown
    validations:
      required: true